language: node_js

node_js:
  - '6'
  - '8'
  - '10'

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

notifications:
  webhooks: https://www.travisbuddy.com/

after_success:
  - npm run cover:alls

sudo: false
